#!/bin/sh 
/usr/bin/myapp
start ()
{
	echo " Starting myapp"
		start-stop-daemon -S -o --background -x $DAEMON
}
stop ()
{
	echo " Stoping myapp"
		start-stop-daemon -K -x $DAEMON
}
restart()
{
	stop
		start
}
[ -e $DAEMON ] || exit 1
case "$1" in
	start)
		start; ;;
	stop)
		stop; ;;
	restart)
		restart; ;;
*)
echo "Usage: $0 {start|stop|restart}"
exit 1
esac
exit $?
