IMAGE_INSTALL_append = " peekpoke"
IMAGE_INSTALL_append = " gpio-demo"
IMAGE_INSTALL_append = " i2csensor"
IMAGE_INSTALL_append = " dialog-control"

IMAGE_INSTALL_append = " myapp-init"
IMAGE_INSTALL_append = " myapp"
IMAGE_INSTALL_append = " testlibusb"
IMAGE_INSTALL_append = " libcaer-lib-and-test"
IMAGE_INSTALL_append = " libcaer"
